replicaCount: 1

image:
  repository: ghcr.io/weaveworks/corp-gh-org-controller
  pullPolicy: IfNotPresent
  tag: "v1.0.0-rc.1"

# required configuration
billingEmail: ""
enterpriseName: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
