apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: corp-gh-org-controller-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: corp-gh-org-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - corp.weave.works
  resources:
  - githuborgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - corp.weave.works
  resources:
  - githuborgs/finalizers
  verbs:
  - update
- apiGroups:
  - corp.weave.works
  resources:
  - githuborgs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: corp-gh-org-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: corp-gh-org-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "corp-gh-org-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: corp-gh-org-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: corp-gh-org-controller-role
subjects:
- kind: ServiceAccount
  name: {{ include "corp-gh-org-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
