
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - corp.weave.works
  resources:
  - githuborgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - corp.weave.works
  resources:
  - githuborgs/finalizers
  verbs:
  - update
- apiGroups:
  - corp.weave.works
  resources:
  - githuborgs/status
  verbs:
  - get
  - patch
  - update
